
services:
  php:
    build: .
    container_name: php-container
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user                # Set the PostgreSQL username
      POSTGRES_PASSWORD: password        # Set the PostgreSQL password (this is the fix)
      POSTGRES_DB: mydb                  # Set the name of the database to be created
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
